### ISSUE TITLE
no scrollbar on results page

### ISSUE THREAD

**Issue by tymonaghan** [tymonaghan/sotu-db#4]
results pages in php do not have scrollbars despite content overflowing the screen

**Comment by tymonaghan** [comment]
@RJP43 pointed out it's the same on the filter list view on index.html. I thought you mentioned something about the viewport thing. But getting rid of that seems to take away the responsiveness.

**Comment by RJP43** [comment]
@tymonaghan I wonder if this [Pull Request](https://github.com/tymonaghan/sotu-db/pull/8) will resolve the issue.

**Comment by tymonaghan** [comment]
Thanks @RJP43 ! testing this morning suggests this is not fixing the issue, but I'll check again later today or tomorrow. Also, there is a newer version of w3.css available. I wonder if we should

- keep using the existing version from October
- update w3.css to the November version and try these changes there
- switch to pulling the w3.css from a url instead of keeping it local, then try to figure out the scrollbar thing with either in-page styles or another stylesheet that overrides w3.css?

**Comment by RJP43** [comment]
Number 3 - then comb HTML for misplaced elements and attributes

**Comment by tymonaghan** [comment]
good news: because it was the php include, changing just the one php file fixed this across pages.

bad news: now every page's top elements are hidden behind the fixed position top-nav bar. Gotta fix that.
